# Generated by Django 4.0.3 on 2022-03-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_options_remove_chat_contacts_chat_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='common', max_length=32),
        ),
    ]
